services:
  node:
    build: node/
    ports:
      - "3000:3001"
    volumes:
      - ./node:/node
      - /node/node_modules
    environment:
      - PORT=3001
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "4000:27017"
    environment:
      - MONGOINITDB_ROOT_USERNAME=admin
      - MONGOINITDB_ROOT_PASSWORD=admin
  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  react:
    build: app/
    ports:
      - "5000:3000"
